version: '3.4'

services:
  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5000:80
    restart: always
      
  mongodb:
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    restart: always
      
volumes:
  mongodb_data: 