version: '3.4'

services:
  catalog.api:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MongoDb: 'mongodb://catalog.mongodb:27017'
      DatabaseName: 'ProductDb'
      CollectionName: 'Products'
    ports:
      - 5000:80
    restart: always
    depends_on:
      - catalog.mongodb
      
  catalog.mongodb:
    ports:
      - 27017:27017
    volumes:
      - catalog.mongodb_data:/data/db
    restart: always
    
  basket.api:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      RedisConnection: basket.redisdb:6379
    ports:
      - 5001:80
    depends_on:
      - basket.redisdb
    restart: always

  basket.redisdb:
    ports:
      - 6379:6379
    volumes:
      - basket.redisdb_data:/data
    restart: always

  portainer:
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    
  discount.api:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 5002:80
    depends_on:
      - discount.postgresdb
    restart: always

  discount.postgresdb:
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1212
      POSTGRES_DB: DiscountDb
    volumes:
      - discount.postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
    
  discount.pgadmin:
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin1234
    ports:
      - 5433:5433
    restart: always
    depends_on:
      - discount.postgresdb

volumes:
  catalog.mongodb_data: 
  basket.redisdb_data:
  discount.postgres_data:
  portainer_data: