version: '3.4'

services:
  catalog.api:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MongoDb: 'mongodb://mongodb:27017'
      DatabaseName: 'ProductDb'
      CollectionName: 'Products'
    ports:
      - 5000:80
    restart: always
    depends_on:
      - mongodb
      
  mongodb:
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    restart: always

  mongoclient:
    ports: 
      - 3000:3000
    restart: always
      
volumes:
  mongodb_data: 