version: '3.4'

services:
  catalog.api:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MongoDb: 'mongodb://catalog.mongodb:27017'
      DatabaseName: 'ProductDb'
      CollectionName: 'Products'
    ports:
      - 5000:80
    restart: always
    depends_on:
      - catalog.mongodb
      
  catalog.mongodb:
    ports:
      - 27017:27017
    volumes:
      - catalog.mongodb_data:/data/db
    restart: always

  catalog.mongoclient:
    ports: 
      - 3000:3000
    restart: always
      
  basket.api:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      RedisConnection: basket.redisdb:6379
    ports:
      - 5001:80
    depends_on:
      - basket.redisdb
    restart: always

  basket.redisdb:
    ports:
      - 6379:6379
    volumes:
      - basket.redisdb_data:/data
    restart: always

  portainer:
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    

volumes:
  catalog.mongodb_data: 
  basket.redisdb_data:
  portainer_data: